apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api-depl
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: beyondnetperu/orders-api:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '200m'
