apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orders-api
spec:
  rules:
    - host:
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: orders-api-service
                port:
                  number: 80
