apiVersion: skaffold/v4beta4
kind: Config
metadata:
  name: services
build:
  artifacts:
    - image: beyondnetperu/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/*
