apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-mysql-deploy
  labels:
    app: mysql
    type: db
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mysql
      type: db
  template:
    metadata:
      labels:
        app: mysql
        type: db
    spec:
      containers:        
        - name: mysql1
          {{- $version:= .Values.version }}        
          {{- if eq .Values.environment "development" }}
          image: mysql:{{$version}}
          {{- else}}
          image: mysql:latest
          {{- end}}
          ports:
            - containerPort: 3306
              name: db-port
          resources:
            requests:
              cpu: {{ .Values.requests.cpu}}
              memory: {{ .Values.requests.memory}}
            limits:
              cpu: {{ .Values.limits.cpu}}
              memory: {{ .Values.limits.memory}}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-data-mysql-env
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-data-mysql-env
                  key: MYSQL_USER
            
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-data-mysql-env
                  key: MYSQL_DATABASE

            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{.Release.Name}}-data-mysql-env
                  key: MYSQL_PASSWORD
