apiVersion: v1
kind: Pod
metadata:
  name: tickets-auth-pod
  labels:
    component: auth
spec:
  containers:
    - name: tickets-auth
      image: beyondnetperu/ticketsauth
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-auth-nodeport
spec:
  type: NodePort
  ports:
    - port: 3051
      targetPort: 3001
      nodePort: 31516
  selector:
    component: auth
