apiVersion: v1
kind: Pod
metadata:
  name: tickets-payments-pod
  labels:
    component: payments
spec:
  containers:
    - name: tickets-payments
      image: beyondnetperu/ticketspayments
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-payments-nodeport
spec:
  type: NodePort
  ports:
    - port: 3054
      targetPort: 3004
      nodePort: 31519
  selector:
    component: payments
