apiVersion: v1
kind: Pod
metadata:
  name: tickets-products-pod
  labels:
    component: products
spec:
  containers:
    - name: tickets-products
      image: beyondnetperu/ticketsproducts
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-products-nodeport
spec:
  type: NodePort
  ports:
    - port: 3055
      targetPort: 3005
      nodePort: 31520
  selector:
    component: products
