apiVersion: v1
kind: Pod
metadata:
  name: tickets-webportal-pod
  labels:
    component: webportal
spec:
  containers:
    - name: tickets-webportal
      image: beyondnetperu/ticketswebportal
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-webportal-nodeport
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
  selector:
    component: webportal
