apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: webportal
  template:
    metadata:
      labels:
        component: webportal
    spec:
      containers:
        - name: tickets-webportal
          image: beyondnetperu/ticketswebportal
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
